version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5000:5000"

  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    container_name: jupyter
    environment:
      - JUPYTER_TOKEN=admin
    volumes:
      - ./jupyter:/home/jovyan/work
      - ./data:/home/jovyan/work/data
      - ./mlflow:/mlflow
    ports:
      - "8888:8888"
    depends_on:
      - mlflow

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: ml_api
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
