services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    container_name: jupyter
    environment:
      - JUPYTER_TOKEN=admin
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - mlflow

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: ml_api
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - mlflow_artifacts:/mlflow/artifacts

volumes:
  mlflow_artifacts:
