FROM jupyter/scipy-notebook:python-3.10

USER root

COPY jupyter/requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN chown -R jovyan:users /home/jovyan/work

USER $NB_UID
