FROM python:3.10-slim

WORKDIR /mlflow

COPY mlflow/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
USER root
RUN mkdir -p /mlflow/artifacts && chmod -R 777 /mlflow/
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5000"]
